"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables de entorno desde .env
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

import dj_database_url

# ------------------------------
# 🔐 SECURITY
# ------------------------------
# En producción, SECRET_KEY debe venir de variables de entorno
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-ef554*i5g#5%90f-(l-8ls4if!jowh&9=am9@&%r&gsg5+#rf0')

# DEBUG debe ser False en producción
DEBUG = 'RENDER' not in os.environ

# Permitir el host de Render
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
else:
    ALLOWED_HOSTS.append('*')


# ------------------------------
# 📦 APPS
# ------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps del proyecto
    'alumnos',
    'scraper',
]


# ------------------------------
# 🔧 MIDDLEWARE
# ------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # Whitenoise → sirve archivos estáticos en Render
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ------------------------------
# 🔗 ROOT URL
# ------------------------------
ROOT_URLCONF = 'mysite.urls'


# ------------------------------
# 🎨 TEMPLATES
# ------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Carpeta global de templates
        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ------------------------------
# 🚀 WSGI
# ------------------------------
WSGI_APPLICATION = 'mysite.wsgi.application'


# ------------------------------
# 🗄 DATABASE
# ------------------------------
DATABASES = {
    'default': dj_database_url.config(
        # Busca la variable DATABASE_URL, si no la encuentra usa sqlite local
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}


# ------------------------------
# 🔐 PASSWORD VALIDATION
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ------------------------------
# 🌎 INTERNATIONALIZATION
# ------------------------------
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True


# ------------------------------
# 🎨 STATIC FILES
# ------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = []
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise en producción
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ------------------------------
# 📄 DEFAULT PRIMARY KEY
# ------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ------------------------------
# 🔐 LOGIN / LOGOUT
# ------------------------------
LOGIN_URL = 'alumnos:login'
LOGIN_REDIRECT_URL = 'alumnos:dashboard'
LOGOUT_REDIRECT_URL = 'alumnos:login'


# ------------------------------
# ✉️ EMAIL - Configuración
# ------------------------------
# MODO CONSOLA: (Desactivado)
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# DEFAULT_FROM_EMAIL = "noreply@gestiondealumnos.com"

# MODO GMAIL SMTP: (Activado)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# PARA ACTIVAR GMAIL:
# 1. Edita el archivo .env con tus credenciales reales de Gmail
# 2. Comenta la línea EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# 3. Descomenta las líneas de GMAIL SMTP arriba
# 4. Reinicia el servidor
